apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: nginx
  # type: LoadBalancer
  # externalTrafficPolicy: Local
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
