apiVersion: apps/v1
kind: Deployment
metadata:
  name: lattest
  labels:
    app: lattest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lattest
  template:
    metadata:
      labels:
        app: lattest
      annotations:
        lat: 50ms
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lattest
spec:
  selector:
    app: lattest
  ports:
    - protocol: TCP
      port: 80
