apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zfsdev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Block
  storageClassName: zfsdev
