apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeipam
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeipam
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - nodeipam
  resources:
  - leases
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aksudrsync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodeipam
subjects:
- kind: ServiceAccount
  name: nodeipam
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeipam
  namespace: kube-system
  labels:
    app: nodeipam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeipam
  template:
    metadata:
      labels:
        app: nodeipam
    spec:
      hostNetwork: true
      serviceAccountName: nodeipam
      containers:
      - name: kube-controller-manager
        # TODO: change to template 
        image: registry.k8s.io/kube-controller-manager:v1.25.2
        args: [
          'kube-controller-manager',
          '--controllers', 'nodeipam',
          '--allocate-node-cidrs',
          '--cluster-cidr', '10.244.0.0/16',
          '--service-cluster-ip-range', '10.0.0.0/16',
          '--leader-elect-resource-name', 'nodeipam',
          '--secure-port', '0'
        ]

