apiVersion: v1
kind: Pod
metadata:
  name: audit-pod-seccomp
  labels:
    app: audit-pod-seccomp
spec:
  nodeSelector:
    kubernetes.io/os: linux
  terminationGracePeriodSeconds: 1
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/ipv4tcpaudit.json
  containers:
  - name: test-container
    image: alpine
    command:
    - sleep
    - inf