apiVersion: v1
kind: Pod
metadata:
  name: test-block
  annotations:
    enable-quickack: "true"
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /quickack-enabled
      name: block-volume
  volumes:
  - name: block-volume
    hostPath:
      path: /var/run/quickack-enabled
      type: File
