apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      enableServiceLinks: false
      dnsPolicy: Default
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.azure.com/agentpool: workpool
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.8.2
        args:
        - --path.rootfs=/host
        - --collector.ethtool
        - --collector.interrupts
        - --collector.processes
        - --collector.softirqs
        - --collector.textfile
        - --collector.textfile.directory=/host/run/text-metrics
        volumeMounts:
        - name: root
          mountPath: /host
          readOnly: true
          mountPropagation: HostToContainer
      volumes:
        - name: root
          hostPath:
            path: /
