scrape_configs:
- job_name: node_exporter
  scrape_interval: 10s
  scrape_timeout: 5s
  kubernetes_sd_configs:
  - role: node
    selectors:
      - role: "node"
        label: "kubernetes.azure.com/agentpool=workpool"
  relabel_configs:
  # - action: labelmap
  #   regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    source_labels: [__address__]
    regex: (.*?)(:\d+)?
    replacement: $1:9100
- job_name: pushgateway
  scrape_interval: 10s
  scrape_timeout: 5s
  static_configs:
  - targets:
    - 127.0.0.1:9091
